version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: navyn
      POSTGRES_PASSWORD: lastP@ssw0rd
      POSTGRES_DB: ghgmgmt
    ports:
      - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: springboot-app
    restart: always
    image: sugirayvan/emissions-log:latest
    depends_on:
      - database
    environment:
      APP_PROFILE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/ghgmgmt
      SPRING_DATASOURCE_USERNAME: navyn
      SPRING_DATASOURCE_PASSWORD: lastP@ssw0rd
    ports:
      - "8088:8088"
    volumes:
        - ./logs:/app/logs