package com.navyn.emissionlog.Enums.Agriculture;

public enum ManureManagementSystem {
    PASTURE_RANGE_PADDOCK,
    DAILY_SPREAD,
    SOLID_STORAGE,
    DRY_LOT,
    LIQUID_SLURRY,
    ANAEROBIC_LAGOON,
    ANAEROBIC_DIGESTER,
    COMPOSTING_INTENSIVE,
    COMPOSTING_STATIC_PILE,
    DEEP_BEDDING,
    POULTRY_MANURE_WITH_LITTER,
    POULTRY_MANURE_WITHOUT_LITTER,
    BURNED_FOR_FUEL
}
