package com.navyn.emissionlog.Enums;

public enum ExcelType {
    FUEL_STATIONARY_EMISSIONS,
    FUEL_TRANSPORT_EMISSIONS,
    VEHICLE_DATA_TRANSPORT_EMISSIONS,
    POPULATION_RECORDS,
    EICV_REPORT,
    SOLID_WASTE_STARTER_DATA,
    INDUSTRIAL_WASTE_STARTER_DATA,
    ZERO_TILLAGE_MITIGATION,
    WETLAND_PARKS_MITIGATION,
}
