package com.navyn.emissionlog.Enums;

public enum TransportType {
    RAIL, AGRICULTURE_EQUIPMENT, FORESTRY_EQUIPMENT, SHIP_AND_BOAT, HOUSEHOLD_EQUIPMENT, CONSTRUCTION_EQUIPMENT, INDUSTRY_EQUIPMENT, MARINE, AIRCRAFT, LAWN_AND_GARDEN_EQUIPMENT, INDUSTRIAL_COMMERCIAL, AIRPORT_EQUIPMENT, INDUSTRIAL_COMMERCIAL_EQUIPMENT, LOGGING_EQUIPMENT, RAILROAD_EQUIPMENT, RECREATIONAL_EQUIPMENT, AGRICULTURAL_EQUIPMENT1, LOCOMOTIVES, CONSTRUCTION_EQUIPMENT2, NONE;
}